### ISSUE TITLE
not able to use as third party library

### ISSUE THREAD

**Issue by mu250234** [jvandemo/generator-angular2-library#254] opened 2017-12-21 18:20 UTC
developing n angular library using "generator-angular2-library" .
when trying to use it from ionic project (lettest version) .
ionic build --prod
 getting following errors .

import  { SampleModule } from 'gen2'; 

Module not found: Error: Can't resolve './app.module.ngfactory' in 'C:\vakaCommonLib\21Dec\ionic\myApp\src\app'
resolve './app.module.ngfactory' in 'C:\vakaCommonLib\21Dec\ionic\myApp\src\app'
  using description file: C:\vakaCommonLib\21Dec\ionic\myApp\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\vakaCommonLib\21Dec\ionic\myApp\package.json (relative path: ./src/app)
    using description file: C:\vakaCommonLib\21Dec\ionic\myApp\package.json (relative path: ./src/app/app.module.ngfactory)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        C:\vakaCommonLib\21Dec\ionic\myApp\src\app\app.module.ngfactory doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        C:\vakaCommonLib\21Dec\ionic\myApp\src\app\app.module.ngfactory.ts doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        C:\vakaCommonLib\21Dec\ionic\myApp\src\app\app.module.ngfactory.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        C:\vakaCommonLib\21Dec\ionic\myApp\src\app\app.module.ngfactory.json doesn't exist
      as directory
        C:\vakaCommonLib\21Dec\ionic\myApp\src\app\app.module.ngfactory doesn't exist
So is this generaotor is useless?

**Comment by anteAdamovic** [comment] 2017-12-30 08:38
@mu250234 You haven't provided steps to reproduce this issue you're having and it's very rude to accuse the writer of this software that his product is useless just because you don't have the knowledge to use it. 

I'm just starting to use it and just did a test for both latest AngularCLI and Ionic and it works on both from start:

AngularCLI: 1.6.3
Angular: 5.0.3
Ionic: 3.9.2
generator-angular2-library: 12.0.0

Voting to close this issue as it can't be reproduced.

**Closed** 2017-12-30 11:39 UTC
