### ISSUE TITLE
ERROR in [Your]Module is not an NgModule...

### ISSUE THREAD

**Issue by ianqueue** [jvandemo/generator-angular2-library#123] opened 2017-06-12 20:00 UTC
Been trying to figure this one out for a couple days now, I'm not really sure what the cause is.

I'm building fine, but when consuming in an @angular/cli app and do a ng serve I get this error and then on a reload it goes away.

Just curious if anyone has run into this and if they know the problem.  I can share code if someone would like...

Using Angular 4.1.3 and cli 1.0.0 stable.  I've tried 1.1.1 also, but same issue.

**Comment by xxxtonixxx** [comment] 2017-06-12 20:19
Hi @ianqueue, can you provide us a demo? 👍

**Comment by ianqueue** [comment] 2017-06-12 21:14
@xxxtonixxx - sure what format?  do you just want my dist/ dir? and someone can go run `ng new` and try and consume it?

**Comment by xxxtonixxx** [comment] 2017-06-13 06:45
if it's possible the entire project, where I can do `npm run build` and to see the configs (tsconfig.json, package.json)

**Comment by jvandemo** [comment] 2017-06-16 04:40
@ianqueue &mdash; Can you please provide the code so we can investigate it?

@xxxtonixxx &mdash; Thank you for offering help, much appreciated! 👍

**Comment by jvandemo** [comment] 2017-06-16 04:46
Here is a related thread in the Angular CLI repository:
https://github.com/angular/angular-cli/issues/3426

I will close this issue for now, but feel free to re-open if you feel the problem is caused by the generator. Thanks again! 👍

**Closed by jvandemo** 2017-06-16 04:46 UTC
