### ISSUE TITLE
Styles from library are not loading

### ISSUE THREAD

**Issue by kajnelissen** [jvandemo/generator-angular2-library#120] opened 2017-06-09 06:09 UTC
I used this generator to create a boilerplate for developing a component library for Angular 4. All these components have separate template and style files. However, when I install the library package in an empty Angular application, the component styles aren't applied. The templates and styles are being inlined and I can see them in the generated `.js` files. The templates and actual code from the library work fine though. Do I need to change a setting or something like that?

An example component in the `js` bundle file looks like this:

    AppComponent.decorators = [
        { type: Component, args: [{
                    selector: "app",
                    styles: ["div[data-width-unit=\"0\"] { font-weight: bold; } h1, h2, h3, h4, h5, h6 { display: inline; }"],
                    encapsulation: ViewEncapsulation.None,
                    template: "<router-outlet></router-outlet>"
                },] },
    ];

**Comment by sebvieira** [comment] 2017-06-09 09:29
Stuck with the same issue for a few days now.

**Comment by jvandemo** [comment] 2017-06-16 05:01
@kajnelissen &mdash; I am unable to reproduce this. The styles are applied correctly when I simulate the same scenario.

Is it possible to share the code of your library? Thanks!

**Comment by alokstar** [comment] 2017-06-19 15:55
Hello All,
I have used the library and facing similar issue. Following is the precise problem:

I have created the sample library as per the instructions, so now I have sample.componet.ts as my main component. Now I have created some new components with their own templates and stylesheets. Now I am using those additional components in the sample.component.ts's view for which I am using sample.component.html. Till now, everything works as expected. 
I can export the library and use it in any external project and can see the library working fine along with the styelesheet changes.

Now, for my library, sample.component.ts is the main component and I have sample.component.html as its view. Now, when I am trying to add new stylesheet for this component like sample.component.less file, all the changes in this sample.component.less are not getting reflected. I wanted to have this stylesheet to change the styling of complete library to be exported.

Pardon me if I misunderstood or misinterpreted anything.
Let me know if you need any more information on the same.

**Comment by kajnelissen** [comment] 2017-06-20 06:19
@jvandemo The problem seems to be related to our specific project (can't share that code unfortunately). I created a small sample application with a library and all styles load fine.

**Comment by alokstar** [comment] 2017-06-20 12:57
@kajnelissen : I am not really sure. It seems like its taking some styles of the stylesheet but not all. Really strange! I guess if you are having multiple components and their respective stylesheets in the library you are developing using 'generator-angular2-library', you can easily reproduce this issue.

**Comment by jvandemo** [comment] 2017-06-26 03:08
@kajnelissen &mdash; Thank you for the update. I will close this issue but feel free to re-open if you feel it is related to this generator. Thanks!

**Closed by jvandemo** 2017-06-26 03:08 UTC
Labels: waiting for more info

**Comment by kajnelissen** [comment] 2017-07-04 13:48
The problem had to do with `ViewEncapsulation`. There was a component with `ViewEncapsulation.None` in the library and I expected its styles to also globally apply in the consuming application. Turns out that that is not the case.
