### ISSUE TITLE
uncaught Error: Unexpected value 'SampleModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by tettus** [jvandemo/generator-angular2-library#22] opened 2016-11-29 17:18 UTC
Hi
 I am getting this error still, any idea? I am using as it is ,havenot modified anything
ncaught Error: Unexpected value 'SampleModule' imported by the module 'AppModule'

**Comment by jvandemo** [comment] 2016-11-29 19:12
@tettus &mdash; This has been reported to be an issue with Webpack. See #18 for the solution. I will close this issue but feel free to re-open if needed. Thanks!

**Closed by jvandemo** 2016-11-29 19:12 UTC

**Comment by tettus** [comment] 2016-11-30 01:18
You know where exactly I have to add this line of code in webpack conf ?

Sent from my HTC

----- Reply message -----

**Comment by tettus** [comment] 2016-11-30 04:30
hi @jvandemo , even after updating it I am still facing the issue...my webpack versions are 
"webpack": "^1.13.0",
    "webpack-dev-server": "^1.14.1",
    "webpack-merge": "^0.14.0",

**Comment by jvandemo** [comment] 2016-12-02 04:39
@tettus &mdash; Did you update your webpack configuration manually as described in https://github.com/jvandemo/generator-angular2-library/issues/18#issuecomment-261769283?

Thanks!

**Comment by sachanacar** [comment] 2017-01-11 01:01
Hi all,

Any idea how someone not using webpack (and using SystemJS instead) can solve that issue?

Cheers!
Sacha

**Comment by IckleChris** [comment] 2017-01-16 00:41
I am still getting this issue in a project built with CLI version `1.0.0-beta.25.5`, despite the fix mentioned in #18 being in CLI.

**Comment by jvandemo** [comment] 2017-01-30 21:33
@sachanacar — Have you found a solution yet for SystemJS? Thanks!

**Comment by jvandemo** [comment] 2017-01-30 21:33
@IckleChris &mdash; Have you managed to get it to work yet? Thanks!

**Comment by sachanacar** [comment] 2017-01-31 01:37
@jvandemo unfortunately no! I found this [issue](https://github.com/angular/angular-cli/pull/2291) which is giving me hope that a fix may be underway?

**Comment by jvandemo** [comment] 2017-01-31 09:17
@sachanacar Thank you, would be great if you could keep us posted if a fix is released. Hopefully soon! 👍

**Comment by IckleChris** [comment] 2017-02-01 10:06
Sorry @jvandemo, I ended up taking a different approach as I could not get it working. Still interested to find out what the cause/solution is though!

**Comment by jvandemo** [comment] 2017-02-01 13:02
@IckleChris &mdash; Thank you, likewise 👍

**Comment by gatimus** [comment] 2017-08-25 18:06
I'm still having this issue, any update?
