### ISSUE TITLE
Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by bagulho** [jvandemo/generator-angular2-library#113] opened 2017-06-01 09:22 UTC
##Bug when linking a recently created library with a vanilla application generated with angular/cli

**Stack Trace:**

> compiler.es5.js:1540 Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.
>     at syntaxError (http://localhost:4200/vendor.bundle.js:5753:34)
>     at http://localhost:4200/vendor.bundle.js:18707:44
>     at Array.forEach (native)
>     at CompileMetadataResolver.webpackJsonp../node_modules/@angular/compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/vendor.bundle.js:18690:49)
>     at JitCompiler.webpackJsonp../node_modules/@angular/compiler/@angular/compiler.es5.js.JitCompiler._loadModules (http://localhost:4200/vendor.bundle.js:29843:66)
>     at JitCompiler.webpackJsonp../node_modules/@angular/compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (http://localhost:4200/vendor.bundle.js:29802:52)
>     at JitCompiler.webpackJsonp../node_modules/@angular/compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (http://localhost:4200/vendor.bundle.js:29764:23)
>     at PlatformRef_.webpackJsonp../node_modules/@angular/core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone (http://localhost:4200/vendor.bundle.js:35662:25)
>     at PlatformRef_.webpackJsonp../node_modules/@angular/core/@angular/core.es5.js.PlatformRef_.bootstrapModule (http://localhost:4200/vendor.bundle.js:35648:21)
>     at Object../src/main.ts (http://localhost:4200/main.bundle.js:20932:124)

**OS:** 
Ubuntu 16.04 x64
**Dep Versions:**
Node - v6.10.2
Npm - 3.3.0
ng-cli - v1.1.0
@ angular/common: 4.1.3
@ angular/compiler: 4.1.3
@ angular/compiler-cli: 4.1.3
@ angular/core: 4.1.3
@ angular/platform-browser: 4.1.3
@ angular/platform-browser-dynamic: 4.1.3

**Steps to reproduce:**
```
yo angular2-library
cd <library folder>
npm link src/
cd ..

ng new sample-app
cd sample-app
npm link <library name>
```

place the folowing code in src/app/app.module.ts
```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { SampleModule } from '_<library name>_';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    SampleModule.forRoot()
  ],
  exports: [
    SampleModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

Serve the application and open in browser

**Comment by robertbrower-technologies** [comment] 2017-06-01 17:58
A solution is presented in issue #111

**Comment by adjioev** [comment] 2017-06-02 01:10
I had the same issue, found answer here: https://github.com/angular/angular-cli/wiki/stories-linked-library

You need to edit /src/tsconfig.app.json in your project (not library!) and add:
~~~~
    "baseUrl": "",
    "paths": {
      "@angular/*": [
        "../node_modules/@angular/*"
      ]
    },  
~~~~

into compilerOptions object.

**Comment by xxxtonixxx** [comment] 2017-06-02 07:12
I have had the same problem, following @adjioev's [comment](https://github.com/jvandemo/generator-angular2-library/issues/113#issuecomment-305661819) I have solve it 😄 

I don't understand why with previous version of ng-cli it works, and doesn't now... And the information to fix it is not clear enough...

Thanks! 👍

**Comment by bagulho** [comment] 2017-06-02 08:10
@robertbrower-technologies I've already tried that before posting this issue and it didn't work.
@adjioev added that paths config you sugested but it also didn't work. Also, shouldn't this be only for compiled output? Please notice that I'm linking to the src/ folder.

**Comment by xxxtonixxx** [comment] 2017-06-02 12:03
hi @bagulho, can you provide us a demo and steps to reproduce your problem? 👍

**Comment by jvandemo** [comment] 2017-06-04 12:23
@adjioev &mdash; Thank you, I have added an additional step in the development guidelines in README as well 👍

**Comment by jvandemo** [comment] 2017-06-04 12:24
@bagulho &mdash; Feel free to provide a copy of your code so we can have a look at it. Thanks!

**Comment by adjioev** [comment] 2017-06-04 23:45
This patch works for default ng 2 project (ng new foobar). If project was updated to work with webpack with the following tutorial: https://angular.io/docs/ts/latest/guide/webpack.html webpack.common.js needs be patched.
Looks like webpack doesn't pick up baseUrl and pathes props, so you need to add 
~~~~
const { TsConfigPathsPlugin } = require('awesome-typescript-loader');
...

  resolve: {
    ....
    plugins: [
      new TsConfigPathsPlugin({
        configFileName: helpers.root('src', 'tsconfig.json'),
        compiler: "typescript",
      })
    ]
  },
~~~~

Of course make sure that /src/tsconfig.json has baseUrl path paths configured as it was described above.

I agree with @xxxtonixxx , this @angular-cli is nuts. In my package.json "@angular/cli": "1.0.0"  works.
but "@angular/cli": "^1.0.0", or "@angular/cli": "1.0.6" fails. It sits in devDependencies so why does it affect runtime?

**Comment by gotnull** [comment] 2017-06-04 23:58
> I agree with @xxxtonixxx , this @angular-cli is nuts. In my package.json "": "1.0.0" works.
but "": "^1.0.0", or "": "1.0.6" fails. It sits in devDependencies so why does it affect runtime?

Can confirm this is happening for me too!

**Comment by bagulho** [comment] 2017-06-05 15:33
Hello
@adjioev suggestion fixed my problem. Not only I placed the fix on the wrong file, but also because my library needs another dependency (ngx-translate) I also nedded to place **"../node_modules/ngx-translate/*"** on the tsconfig file
Thanks all

**Comment by jvandemo** [comment] 2017-06-26 03:34
@adjioev &mdash; Thanks again for sharing the solution. Instructions have been added to the README. I will close this issue but feel free to re-open if needed 👍

**Closed by jvandemo** 2017-06-26 03:34 UTC
Labels: fix suggested, question

**Comment by quahkj** [comment] 2017-08-11 04:19
@jvandemo - I think I encounter this issue again with the latest Angular cli:

```
Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (compiler.es5.js:1690)
    at compiler.es5.js:15382
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver.getNgModuleMetadata (compiler.es5.js:15365)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._loadModules (compiler.es5.js:26795)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (compiler.es5.js:26768)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (compiler.es5.js:26697)
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_._bootstrapModuleWithZone (core.es5.js:4536)
    at PlatformRef_.webpackJsonp.../../../core/@angular/core.es5.js.PlatformRef_.bootstrapModule (core.es5.js:4522)
    at Object.../../../../../src/main.ts (main.ts:11)
```

Environment: Apple MacOS, node (v6.11.2), npm (v.5.3.0), angular cli (v1.3.0)

I upgraded all above tools to the latest version then generate the library and try to consume with angular cli consumer but keep getting above error in the console. Please take note I have used the solution proposed above by configuring src/tsconfig.app.json:

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    **"paths": {
        "@angular/*": [
            "../node_modules/@angular/*"
        ]
    },**
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```
I am running out of idea on this issue. I am appreciate if anyone out there can help or encounter this issue as well. Thanks!

**Comment by saberhamidi** [comment] 2017-08-14 17:49
same problem. I have already edit src/tsconfig.app.json, please help.

**Comment by daslaf** [comment] 2017-08-14 17:55
I can confirm I'm getting the same error with angular cli v1.3.0

**Comment by shanthece** [comment] 2017-08-18 10:25
I can confirm this exactly happening to me

**Comment by jpconsi** [comment] 2017-08-22 04:49
@daslaf I found that with the latest versions of angular cli (v1.3.0 and 1.3.1) that you must remove 
` "paths": {
      "@angular/*": [
        "../node_modules/@angular/*"
      ]
    }`

from tsconfig.app.json. This is because the latest version of angular-cli use the patched version of ngtools/webpack so the original issue that required the use of "paths" in the tsconfig.app.json is no longer necessary and I also found it had to be removed or angular-cli will error.

**Comment by daslaf** [comment] 2017-08-22 08:09
@jpconsi yes, I already applied the fix suggested in #170 by @jvandemo which is now in the docs, but thanks anyways =)

**Comment by ramanansivagnanam** [comment] 2018-06-13 04:12
Uncaught Error: Unexpected value '[object Object]' declared by the module 'AppModule'
    at syntaxError (compiler.js:215)
    at compiler.js:10508
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (compiler.js:10506)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules (compiler.js:22567)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:22548)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler.compileModuleAsync (compiler.js:22508)
    at CompilerImpl.push../node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:143)
    at PlatformRef.push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule (core.js:4199)
    at Object../src/main.ts (main.ts:11)

Facing this error
I am a beginer too
help me out friends
Thanks in Advance

**Comment by niharika2812** [comment] 2018-06-18 11:53
Getting the same error@
ramanansivagnanam

**Comment by ramanansivagnanam** [comment] 2018-06-20 14:44
i crashed that app ;)
